# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"

skin: "/assets/css/skins/dark.css"
locale: en-GB
title: Han Dance
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  AN INTRO HERE.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

date_format: "%d-%m-%Y"

#read_time: true
#words_per_minute: 200

mathjax: 
  enable: true

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i" 

#Liquid
liquid:
  error_mode: strict


# Build settings
markdown: kramdown
feed:
  path: atom.xml

paginate: 10
paginate_path: /page:num/


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

#Collections
collections:
  Portfolio:
    output: true
    permalink: /:collection/:path/


# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false
  # Recipe defaults
  - scope:
      path: "_Portfolio"
      type: Portfolio
    values:
      layout: post
      comments: false
      share: false

# Footer Links
footer_links:
  - title: LinkedIn
    url: https://uk.linkedin.com/in/han-dance-964944122
    icon: fab fa-linkedin


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
